BHoM/MidasCivil_Toolkit

- MidasCivil_Engine/Convert/ToBHoM/Properties/ToConstraint6DOF.cs
- MidasCivil_Engine/Convert/ToMidasCivil/Elements/FromFEMesh.cs
- MidasCivil_Engine/Query/SupportString.cs
Closes #182
Closes #184 
Closes  #186 
- Fixed bug where `FEmesh `could not be pushed without a `Material` or a `SurfaceProperty` assigned
- Fixed bug where `Constraint6DOF` was not pushing correctly
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FMidasCivil%5FToolkit%2FMidasCivil%5Ftoolkit%2D%23182
- Fixed bug where `FEmesh `could not be pushed without a `Material` or a `SurfaceProperty` assigned
- Fixed bug where `Constraint6DOF` was not pushing correctly
- Fixed bug where `Constraint6DOF` with spring stiffnesses were not read correctly on 8.8.5
> Bug fixes for Property objects assigned to elements

- MidasCivil_Adapter/CRUD/Read/Results/BarResults.cs
- MidasCivil_Adapter/CRUD/Read/Results/MeshResults.cs
- MidasCivil_Adapter/CRUD/Read/Results/NodeResults.cs
- MidasCivil_Adapter/CRUD/Read/Results/ReadResults.cs
- MidasCivil_Adapter/MidasCivil_Adapter.csproj
- MidasCivil_Adapter/Type/NextFreeId.cs
- MidasCivil_Adapter/packages.config
- MidasCivil_Engine/Convert/ToBHoM/Results/ToNodeDisplacement.cs
- MidasCivil_Engine/Convert/ToBHoM/Results/ToNodeReaction.cs
- MidasCivil_Engine/MidasCivil_Engine.csproj
- MidasCivil_Engine/packages.config
Closes #173 
Closes #188 
MidasCivil `NodeReaction `results (as an Excel file) can be read
MidasCivil `NodeDisplacement`results (as an Excel file) can be read
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/MidasCivil_Toolkit/MidasCivil_Toolkit-%23173?csf=1&e=q2tImG
@StephennipBH when reviewing can you follow this workflow please:
1. Delete any existing .csv or .xls files in the folder
2. Remove any existing text files
3. Export the .mct file from the model 
4. Run the adapter
5. Export Global NodeReaction and NodeDisplacement as an .xls file from MidasCivil (sort by Node then Load)
6. Run the test script for NodeReaction and NodeDisplacement
**Note: When you are checking the results, sort by Node and Load for easy comparison between Result …
> Add read functionality for NodeReaction and NodeDisplacement

- MidasCivil_Adapter/CRUD/Read/Elements/Bars.cs
- MidasCivil_Adapter/MidasCivil_Adapter.csproj
- MidasCivil_Adapter/PrivateHelpers/SectionMaterialCombinations.cs
- MidasCivil_Engine/Convert/ToBHoM/Elements/ToBar.cs
- MidasCivil_Engine/Convert/ToBHoM/Properties/ToMaterials.cs
- MidasCivil_Engine/Convert/ToBHoM/Properties/ToSectionProperty.cs
Closes #198 
- `SectionProperty` now read as a `GenericSection `
- Casting of `ISectionProperty `to `SteelSection`, `ConcreteSection `etc. is done at Adapter level
- Unique list of `SectionProperty`/`Material `combinations generated and fed in to Convert.ToBar(..)
https://burohappold.sharepoint.com/:f:/s/BHoM/ElOqrdbYH0dDsulwV4dm-XIBmvigR3XIam-P1we2UFDgTg?e=5STKqN
- `SectionProperty` now read as a `GenericSection `
- Casting of `ISectionProperty `to `SteelSection`, `ConcreteSection `etc. is done at Adapter level
- Unique list of `SectionProperty`/`Material `combinations generated and fed in to Convert.ToBar(..)
> Read SectionProperty and Material when reading a Bar

- MidasCivil_Adapter/CRUD/Read/Results/ReadResults.cs
This will fix the problem for now, recommend that a more effective solution would be to also filter by file type to make sure that it is an excel file type being inserted into the function.
Closes #196 
https://burohappold.sharepoint.com/:f:/s/BHoM/ElUYnAEfM75CmIYz7SvR_nIBQVzFj7681FMOmP2XOYlmHQ?e=acWWof
> Records an error if the excel file it is searching for doesn't exist

- MidasCivil_Adapter/CRUD/Read/Results/BarResults.cs
- MidasCivil_Adapter/CRUD/Read/Results/MeshResults.cs
Closes #215 
Changed method from `private` to `public` to fix a bug in pulling results from Midas.
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FMidasCivil%5FToolkit%2FMidasCivil%5FToolkit%2D%23190
The workflow for reviewing pulling results @peterjamesnugent :
- Delete any existing .csv or .xls files in the folder
- Remove any existing text files
- Export the .mct file from the model
- Run the adapter
- Export Global `Beam Force` , `Beam Stress` and `Plate Force(UL_Local)` as an .xls file from MidasCivil
- Run the test script for `BarForce` , `BarStress` and `MeshForce`
**Note: When you are checking …
> Changing method from private to public

- MidasCivil_Adapter/CRUD/Read/Results/BarResults.cs
- MidasCivil_Adapter/CRUD/Read/Results/MeshResults.cs
- MidasCivil_Adapter/CRUD/Read/Results/ReadResults.cs
- MidasCivil_Adapter/Convert/ToBHoM/Results/ToMeshStress.cs
- MidasCivil_Adapter/Convert/ToBHoM/Results/ToMeshVonMises.cs
- MidasCivil_Adapter/MidasCivil_Adapter.csproj
Closes #214  
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FMidasCivil%5FToolkit%2FMidasCivil%5FToolkit%2D%23190
Added functionality to read `MeshStress` results
Added functionality to read `MeshVonMises` results
@peterjamesnugent  when reviewing can you follow this workflow please:
- Delete any existing .csv or .xls files in the folder
- Remove any existing text files
- Run the adapter
- Export excel result named `Plate Stress(L)` as an .xls file from MidasCivil
- Run the test script for `MeshStress`.
- Change the filter request for `MeshVonMises` and test it.
**Note: When you are checking the …
> Added functionality to read remaining MeshResults

- MidasCivil_Adapter/CRUD/Read/Loads/BarPointLoads.cs
- MidasCivil_Adapter/CRUD/Read/Loads/BarUniformlyDistributedLoad.cs
- MidasCivil_Adapter/CRUD/Read/Loads/BarVaryingDistributedLoads.cs
- MidasCivil_Adapter/CRUD/Read/Loads/GravityLoads.cs
- MidasCivil_Adapter/Convert/ToBHoM/Loads/ToGravityLoad.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToSectionProperty.cs
- MidasCivil_Adapter/PrivateHelpers/GetSectionText.cs
- MidasCivil_Adapter/PrivateHelpers/GetTags.cs
- MidasCivil_Adapter/PrivateHelpers/WriteSectionText.cs
- README.md
Closes #225 
Closes #227 
Closes #228 
Closes #229 
https://burohappold.sharepoint.com/:f:/s/BHoM/EtPgDV8xjf5Dtu5THK-BpJ8BxZe7XfRLQ1nXUlGHHlY_Wg?e=BBh5sm
- Added string.Trim() to strings being read from MCT files to ensure section names are correct 
- Fixed bug where reading `ISection` from MidasCivil used a deprecated method and produced inconceivable sections
- Fixed bug where `BarPointLoad`, BarUniformlyDistributedLoad` and `BarVaryingDistributedLoad` referenced the wrong index for `Name` properties
- Fixed bug where `GravityLoad` referenced the wrong indexes
- Removed official support for MidasCivil, the majority of functionality should still work but we are unable to test MidasCivil 2018 in particular GravityLoad which was causing issues for Midas Civil 2019 onwards 
Three tests:
1. …
> Various bug fixes for reading from MidasCivil

- MidasCivil_Adapter/Convert/ToBHoM/Elements/ToRigidLink.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromRigidLink.cs
/BHoM/BHoM/pull/961
Closes #
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Structure_oM/Issue921-RigidLink%20property%20rename/Test%20Rigid%20Links%20-%20multi%20adapter.gh?csf=1&web=1&e=iDXtGs
> Renamed RigidLink master/slave to primary/secondary

- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToConstraint6DOF.cs
Closes #239 
The reading of  `Constraint6DOF` is corrected when pulling from Midas.
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?originalPath=aHR0cHM6Ly9idXJvaGFwcG9sZC5zaGFyZXBvaW50LmNvbS86Zjovcy9CSG9NL0VvTXpaNlBnSjc5R3BuUjBNNjMtNzZ3QjdKMGVEa04tRVlMVll6VG14Y0NyWWc%5FcnRpbWU9RlBuN2tTMUMyRWc&sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FMidasCivil%5FToolkit%2FMidasCivil%5FToolkit%2D%23239
Changed the command in converting fixity from Midas to BHoM.
@peterjamesnugent  when reviewing, you can use the test script to filter request `Constraint6DOF`. It should provide you with the correct fixity of the two test nodes.
> Correct bug in reading the fixity value

- MidasCivil_Adapter/MidasCivilAdapter.cs
Closes #238 
https://burohappold.sharepoint.com/:f:/s/BHoM/EsQr7IbtAVhIqRnhqLvLtvUBAVay3L_gYfpahYup1A_84g?e=eLTcCH
> Added catch statement for ArguementOutOfRangeException when no MCT or Units.txt is provided 

- MidasCivil_Adapter/CRUD/Create/Properties/SectionProperties.cs
- MidasCivil_Adapter/CRUD/Read/Properties/SectionProperties.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToSectionProperty.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Properties/FromSectionProperty.cs
https://github.com/BHoM/BHoM/pull/992
https://github.com/BHoM/BHoM_Engine/pull/1980
Closes #244 
https://burohappold.sharepoint.com/:f:/s/BHoM/EoQuT-hlPLVJpbYy2JulBl4B9ZZJxhUHUUDXFB40ncF1cA?e=RDh0aQ
- @StephennipBH can you push/pull a few `SectionProfile` types please as I have made changes to that code too.
- MidasCivil only accepts the start and end profile.
> Added support for creating and reading TaperedProfile

- MidasCivil_Adapter/AdapterActions/Execute.cs
- MidasCivil_Adapter/CRUD/Read/Results/BarResults.cs
- MidasCivil_Adapter/CRUD/Read/Results/MeshResults.cs
- MidasCivil_Adapter/CRUD/Read/Results/NodeResults.cs
- MidasCivil_Adapter/MidasCivilAdapter.cs
- MidasCivil_Adapter/MidasCivil_Adapter.csproj
Closes #264 
https://burohappold.sharepoint.com/:f:/s/BHoM/ErxmGOmmN8NBgJlqNkc3AbYBeORcs5tkjRCKIUEbgCxQJQ?e=sAdf2k
- Added `AdapterActions` such as `NewModel`, `OpenFile`, `SaveAs` and `ClearResults`
- Migrated the expected directory for results to `m_directory\Results` similar to where TextFiles are stored (`m_directory\TextFiles`)
- This allows for the easy removal of the `Results` directory when invoking `ClearResults`
- When `NewModel` is invoked, the `Units` and `MidasCivilVersion` files (if available) will be copied, otherwise they will default SI Units and the default `MidasCivilVersion` which is currently `8.8.1`
- When `SaveAs` is invoked, all the files in the `\TextFiles` and `\Results\` folders will be copied over along with the `.mcb` and `.mct` file
> Add various AdapterActions

- MidasCivil_Adapter/AdapterActions/Execute.cs
- MidasCivil_Adapter/CRUD/Read/Properties/SurfaceProperty.cs
- MidasCivil_Adapter/MidasCivilAdapter.cs
- MidasCivil_Engine/MidasCivil_Engine.csproj
Closes #251 
Closes #286 
- Changed when a default `m_midasCivilVersion` was set 
- Made `m_midasCivilVersion` `public` so it is viewable from exploding the `Adapter`
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/Archive/MidasCivil_Toolkit/MidasCivil_Toolkit-%23286?csf=1&web=1&e=2xc3Iy
- Fixed a bug the `m_midasCivilVersion` was defaulting to 8.8.1 despite using an override within the adapter
> Fix bug where *VERSION was not correctly set

- MidasCivil_Adapter/CRUD/Create/Loads/AreaUniformTemperatureLoads.cs
- MidasCivil_Adapter/CRUD/Create/Loads/AreaUniformlyDistributedLoads.cs
Closes #296 
Fixes bug where loads were not being applied to all `FEMeshFace` when an `FEMesh` with multiple `FEMeshFaces` was pushed to MidasCivil.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23296_Area_Loading/GenericPushGeometryToMidasScript.gh?csf=1&web=1&e=MGdA95
> Fix bug where loads are not applied to FEMesh objects that have more than one FEMeshFace

- MidasCivil_Adapter/CRUD/Create/Create.cs
- MidasCivil_Adapter/CRUD/Create/Loads/AreaDifferentialTemperatureLoad.cs
- MidasCivil_Adapter/CRUD/Read/Loads/AreaDifferentialTemperatureLoad.cs
- MidasCivil_Adapter/CRUD/Read/Loads/ReadLoad.cs
- MidasCivil_Adapter/Convert/ToBHoM/Loads/ToAreaDifferentialTemperatureLoad.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromAreaDifferentialTemperatureLoad.cs
- MidasCivil_Adapter/MidasCivil_Adapter.csproj
Closes #271 
This is the same PR as #292. Please go to #292 for previous comments.
Added support for writing `AreaDifferentialTemperatureLoad`.
Added support for reading `AreaDifferentialTemperatureLoad`.
Please note that this feature is only  supports input for `TopPosition` and `BottomPosition`. In Midas, the `AreaDifferentialTemperatureLoad` is inputted as a combination of `ElementTemperatures` and `TemperatureGradient`.
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?cid=506a082e%2Daf0c%2D43ad%2D8fb5%2D4505bb1e26bb&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FArchive%2FMidasCivil%5FToolkit%2FMidasCiv …
> Added create/read support for AreaDifferentialTemperatureLoad

- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToSectionProperty.cs
Closes #304 
This PR would address the issue with error caused by pulling Midas_Created symmetrical section properties. The changes have been made on `ChannelSection`, `ISection` and `BoxSection`.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23304-Corbel%20width%20bug%20on%20box%20sections?csf=1&web=1&e=0zpZXx
> Fixed bug where sections created in MidasCivil would be incorrectly assigned a corbel width

- MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromAreaDifferentialTemperatureLoad.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromBarDifferentialTemperatureLoad.cs
- MidasCivil_Adapter/PrivateHelpers/CompareLoadGroup.cs
Closes #307 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/Installers/Scripts/BuroHappold_BHoM_v4.2/Structures%20-%20Create%20read%20loads?csf=1&web=1&e=IbHwj6
- Fixed a bug where loads with names that were contained in load names already pushed would not be pushed. For example a `barPointLoad.Name = BarPointLoad-1` is pushed, trying to push `pointLoad.Name = PointLoad-1` would not succeed,
- Fixed a bug where the `BarDifferentialTemperatureLoad` was not assigned a Load Group in MidasCivil corresponding to its name
> Fix bug in CompareLoadGroup

- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs
- MidasCivil_Adapter/Convert/ToBHoM/Results/ToBarForce.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Properties/FromSectionProperty.cs
- MidasCivil_Adapter/Convert/Units/ForceToSI.cs
- MidasCivil_Adapter/Convert/Units/MomentFromSI.cs
- MidasCivil_Adapter/Convert/Units/MomentToSI.cs
- MidasCivil_Adapter/Convert/Units/PressureFromSI.cs
- MidasCivil_Adapter/Convert/Units/PressureToSI.cs
Closes #288
Closes #311 
Closes #313
Closes #314  
[Results unit conversion and moment sign convention](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23288-Fixed%20sign%20convention%20and%20units%20bug?csf=1&web=1&e=KW9Ug2)
[Pushing/Pulling GeneralisedFabricatedBoxSection](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23313-Pushing%20corbel%20width%20on%20box%20sections?csf=1&web=1&e=PrvxCe)
[Checking box sections with different parameters can still be pulled from MidasCivil](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23304-Corbel%20width%20bug%20on%20box%20sections?csf=1&web=1&e=0zpZXx)
- Fixed a bug …
> Fixed sign convention and units bug

- MidasCivil_Adapter/Convert/ToBHoM/Elements/ToBar.cs
- MidasCivil_Adapter/Convert/ToBHoM/Elements/ToNode.cs
- MidasCivil_Adapter/Convert/ToBHoM/Elements/ToRigidLink.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToBarRelease.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToSurfaceProperty.cs
Done is support of, but compiles without https://github.com/BHoM/BHoM_Engine/pull/2738
Align with removed methods from Structure_Engine
> Align with changes in Structure_Engine

- MidasCivil_Adapter/CRUD/Create/Loads/AreaUniformlyDistributedLoads.cs
- MidasCivil_Adapter/CRUD/Create/Loads/PointForce.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToConstraint6DOF.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToSurfaceProperty.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromAreaUniformlyDistributedLoad.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromLoadCombination.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromPointForce.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Properties/FromSpring.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Properties/FromSurfaceProperty.cs
- MidasCivil_Adapter/PrivateHelpers/GetPropertyAssignments.cs
Closes #334 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23335-Add%20support%20for%20MidasCivil%202022%20v2.2?csf=1&web=1&e=0l7Zcw
-  Added support for MidasCivil 2021 (all versions) to MidasCivil 2022 (up to v2.1) which only impacts `SurfaceProperty`, `Constaint6DOF` and `LoadCombination`
- Fixed bug where `AreaUniformlyDistributedLoads` were not being pushed as the parsing had been amended in 9.1.0.
> Add support for MidasCivil 2022 

- MidasCivil_Adapter/MidasCivilAdapter.cs
Closes #343
Temporary turn off caching system
> Temporarily turning off caching system

- MidasCivil_Adapter/CRUD/Create/Elements/RigidLink.cs
- MidasCivil_Adapter/CRUD/Read/Elements/RigidLinks.cs
- MidasCivil_Adapter/Convert/ToBHoM/Elements/ToRigidLink.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToBarRelease.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToConstraint6DOF.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToSurfaceProperty.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromRigidLink.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromAreaDifferentialTemperatureLoad.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromAreaUniformlyDistributedLoad.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromLoadCombination.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromPointForce.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Properties/FromFixity.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Properties/FromSpring.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Properties/FromSurfaceProperty.cs
- MidasCivil_Adapter/MidasCivilAdapter.cs
- MidasCivil_Adapter/PrivateHelpers/AssignBarRelease.cs
- MidasCivil_Adapter/PrivateHelpers/GetBarReleaseAssignments.cs
- MidasCivil_Adapter/PrivateHelpers/GetPropertyAssignments.cs
- MidasCivil_Adapter/PrivateHelpers/GetSectionMaterialCombinations.cs
Closes #341 
Closes #351 
Closes #353 
[Push/Pull Elements](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23351%20Add%20support%20for%20MidasCivil%202023%20v1.1/BuroHappold_BHoM_v6.1.beta_Create%20-%20read%20-%20elements%20-%20bridges.gh?csf=1&web=1&e=euHVY5)
[Push/Pull Loads](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23351%20Add%20support%20for%20MidasCivil%202023%20v1.1/BuroHappold_BHoM_v6.1.beta_Create%20read%20loads.gh?csf=1&web=1&e=uWBM23)
[Push/Pull `RigidLink` and `BarRelease`](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23353%20Fixes%20for%20RigidLink/%23353%20Bug%20fix%20for%20RigidLink.gh?cs …
> Add support for MidasCivil 2023 v1.1 and bug fixes

- MidasCivil_Adapter/CRUD/Create/Properties/SectionProperties.cs
- MidasCivil_Adapter/CRUD/Read/Properties/SectionProperties.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToSectionProperty.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Properties/FromSectionProperty.cs
- MidasCivil_Adapter/PrivateHelpers/GetAssignmentIds.cs
- MidasCivil_Adapter/PrivateHelpers/SetSectionText.cs
- MidasCivil_Adapter/Type/NextFreeId.cs
Closes #332 
[Push and pull](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23332%20Add%20Freeform%20Profiles?csf=1&web=1&e=TOnDcs)
Added support for pushing `FreeformProfile` 
Added support for pulling PSC-Value General sections
~The Shear Factor for Shear Stress (Qby, Qbz) is not clear how to calculate it for PSC-Value sections - I have contacted Midas regarding this.~ Added calculation.
~The Asy and Asz is also different to what our integration method is calculation - so will need some testing.~ Will leave it based on integration methods.
~There is also a visual bug for plates at 40mm.~ Purely visual.
Tickets raised here:
https://globalsupport.midasuser.com/helpdesk/Ticket/61518403 …
> Add support for pushing and pulling of custom sections

- MidasCivil_Adapter/CRUD/Read/Properties/Materials.cs
- MidasCivil_Adapter/CRUD/Read/Properties/SectionProperties.cs
- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToMaterials.cs
- MidasCivil_Adapter/PrivateHelpers/GetSectionMaterialCombinations.cs
Closes #356 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23356%20Custom%20Sections%20Not%20Supported?csf=1&web=1&e=OQFqUA
- Changed the way `SectionProperties` are read to capture unsupported sections from MidasCivil.
- Improved the database searching when pulling database `SectionProperty` and `IMaterialFragment` from MidasCivil
> Add statement to identify start of section inputs to simplify statements for skipping unsupported sections

- MidasCivil_Adapter/Type/NextFreeId.cs
Closes #359 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23359-SectionPropertyIdBug.gh?csf=1&web=1&e=iWCRtf
- Fixed bug where `SectionProperty` objects did not have sequential ids when using multiple push components, leading to errors when trying to read them in to a `Dictionary`.
> Fix bug where SectionProperty ids were not sequential for multiple pushes

- MidasCivil_Adapter/Convert/ToBHoM/Properties/ToSurfaceProperty.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Properties/FromSurfaceProperty.cs
Closes #361 
Changed how `SurfaceProperty` names are read from MidasCivil
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23361%20CreateNonExisting?csf=1&web=1&e=JVUdLf
- Fixed a bug whereby `SurfaceProperty` names were not being read from MidasCivil.
> Changing how SurfaceProperty Name is handled for MidasCivil 2020 v3.2

- MidasCivil_Adapter/AdapterActions/Execute.cs
The copying of the `.mcb` and `.mct` file when using the `SaveAs` command did not work. It used the wrong input for the `File.Copy(string, string)`. The second string pointed to a `directory` rather than a `destination file`.
This made it so the `.mcb` and `.mct` file was not copied.
The issue also resulted in the issue stated in #289 which this closes.
Closes #289 
Please use the test script below and run the execute workflow.
Before testing
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&web=1&e=bdWLDi&cid=c70586d3%2Df382%2D473f%2Dab89%2Db962fae9a4aa&RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FMidasCivil%5FToolkit%2F%23289%2DSaveAsNotWorking&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4
> Fixed bug where SaveAs command caused an error

- MidasCivil_Engine/Compute/CombineTextFiles.cs
Closes #180 
Fix bug where mct file failes to run with error message. 
> Error has been encountered during the data input. : *The command of REBAR-MATL-CODE cannot be executed when nodes or sections are included in the model.
> Run Error : command in line 8-10
Fixed by not including REBAR-MATL-CODE when nodes or sections are included. 
- Very simple push and combine script. 
- MidasCivil file with one node existing. 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Lusas_Toolkit/%23373-FixBugWithMctFailsToParse?csf=1&web=1&e=vm1gbm
> Fix a bug where REBAR-MATL-CODE creates an error when running mct file

- MidasCivil_Adapter/CRUD/Create/Elements/Element.cs
- MidasCivil_Adapter/CRUD/Create/Properties/BarReleases.cs
- MidasCivil_Adapter/PrivateHelpers/AssignBarRelease.cs
Closes #375 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23375-FRAME-RLS.gh?csf=1&web=1&e=Uyp9b0
- Removed code that would filter `FixFix` `BarRelease` and result in empty `BarRelease`s being pushed to MidasCivil, this would result in a warning
- Fixed a bug whereby partial matches would result in the incorrect assignments of BarReleases
> Remove FixFix exception and remove bug for partial matches

- MidasCivil_Adapter/CRUD/Create/Loads/AreaUniformlyDistributedLoads.cs
- MidasCivil_Adapter/CRUD/Create/Loads/BarPointLoads.cs
- MidasCivil_Adapter/CRUD/Create/Loads/BarUniformlyDistributedLoads.cs
- MidasCivil_Adapter/CRUD/Create/Loads/BarVaryingDistributedLoads.cs
Closes #274 
[#274 BarVaryingDistributedLoad](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23274%20BarVaryingDistributedLoad.gh?csf=1&web=1&e=XaNAnJ)
- Changed how `BarVaryingDistributedLoads` are created  to remove any modification of the base object;
> Shallow clone BarVaryingDistributedLoad so the returned objects are not modified

- MidasCivil_Adapter/CRUD/Create/Loads/BarVaryingDistributedLoads.cs
- MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromBarVaryingDistributedLoad.cs
Closes #270 
https://burohappold.sharepoint.com/:u:/s/BHoM/EcypvhJiU-xChY8dJfVL-8sBTSXaNxMPg5VcWCp9IGC-8w?e=Mdwfdm
- Added support for `BarVaryingDistributedLoad` with absolute distances.
> Add absolute distances `BarVaryingDistributedLoad`
