BHoM/MidasCivil_Toolkit

MidasCivil_Adapter/CRUD/Read/Results/BarResults.cs
MidasCivil_Adapter/CRUD/Read/Results/MeshResults.cs
MidasCivil_Adapter/CRUD/Read/Results/NodeResults.cs
MidasCivil_Engine/Convert/ToBHoM/Results/ToBarForce.cs
MidasCivil_Engine/Convert/ToBHoM/Results/ToBarStress.cs
MidasCivil_Engine/Convert/ToBHoM/Results/ToMeshForce.cs
MidasCivil_Engine/Convert/ToBHoM/Results/ToNodeReaction.cs
MidasCivil_Engine/MidasCivil_Engine.csproj

Closes #189 
Closes #190 
Closes #191 
MidasCivil `BeamForce` results (as an Excel file) can be read
MidasCivil `BeamStress` results'(as an Excel file) can be read
MidasCivil `MeshForce` results'(as an Excel file) can be read
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FMidasCivil%5FToolkit%2FMidasCivil%5FToolkit%2D%23190
@ismaelibrahim  when reviewing can you follow this workflow please:
- Delete any existing .csv or .xls files in the folder
- Remove any existing text files
- Export the .mct file from the model
- Run the adapter
- Export Global `Beam Force` , `Beam Stress` and `Plate …

Add read functionality for BarForce, BarStress and MeshForce

---

README.md

Closes #217 
https://github.com/BHoM/MidasCivil_Toolkit/tree/MidasCivil_Toolkit-217-UpdateAzurePipelineBadgeInReadMe

Fixed incorrect reference for Azure Pipeline badge in ReadMe

---

MidasCivil_Adapter/MidasCivil_Adapter.csproj
MidasCivil_Engine/MidasCivil_Engine.csproj
MidasCivil_oM/MidasCivil_oM.csproj

https://github.com/BHoM/admin/issues/5

Update postbuild events and project references

---

MidasCivil_Adapter/CRUD/Read/Results/BarResults.cs
MidasCivil_Adapter/CRUD/Read/Results/MeshResults.cs
MidasCivil_Adapter/CRUD/Read/Results/NodeResults.cs
MidasCivil_Adapter/CRUD/Read/Results/ReadResults.cs
MidasCivil_Adapter/MidasCivil_Adapter.csproj
MidasCivil_Engine/MidasCivil_Engine.csproj

https://github.com/BHoM/BHoM/pull/911
Aligning with migration of Results from Common_oM to Analytical_oM.
Also, removing reference to Common_oM as no longer needed.

Aligning with changes migrating Results to Analytical_oM

---

MidasCivil_Adapter/Convert/ToBHoM/Results/ToBarForce.cs
MidasCivil_Adapter/Convert/ToBHoM/Results/ToBarStress.cs
MidasCivil_Adapter/Convert/ToBHoM/Results/ToMeshForce.cs
MidasCivil_Adapter/Convert/ToBHoM/Results/ToMeshStress.cs
MidasCivil_Adapter/Convert/ToBHoM/Results/ToMeshVonMises.cs
MidasCivil_Adapter/Convert/ToBHoM/Results/ToNodeDisplacement.cs
MidasCivil_Adapter/Convert/ToBHoM/Results/ToNodeReaction.cs

https://github.com/BHoM/BHoM/pull/912
Align with changes in Structure_oM making results immutable
https://burohappold.sharepoint.com/:f:/s/BHoM/EvGtuSxnW1dIrSVd2Ngna-8Bc8XLFqTdwtVxu05g8-BDew?e=088OI7

Align with changes in Structure_oM making results immutable

---

README.md

Closes #222 
https://github.com/BHoM/MidasCivil_Toolkit/tree/MidasCivil_Toolkit-222-UpdateReadMeToReflectVersionsofMidasCivilSupported

Update README.md to reflect versions of MidasCivil supported

---

MidasCivil_Adapter/CRUD/Read/Read.cs
MidasCivil_Adapter/CRUD/Read/Results/ReadResults.cs

https://github.com/BHoM/BHoM_Adapter/pull/244
Closes #232
https://burohappold.sharepoint.com/:f:/s/BHoM/EoMzZ6PgJ79GpnR0M63-76wB7J0eDkN-EYLVYzTmxcCrYg?e=WBOld4
- Removed support for pulling results with `FilterRequest`
- Added error message and recommended `ResultRequest` when using `FilterRequest` to pull results

Removed support for pulling results with FilterRequest

---

MidasCivil_Adapter/Convert/ToBHoM/Elements/ToPanel.cs
MidasCivil_Engine/Compute/FEMeshToPanel.cs

Changes here should compile to master, but are required by:
https://github.com/BHoM/BHoM_Engine/pull/1942
Updating old PanelPlanar creates.

Aligning with changes to Panel creates

---

MidasCivil_Adapter/CRUD/Read/Properties/SectionProperties.cs
MidasCivil_Adapter/Convert/ToBHoM/Properties/ToProfile.cs
MidasCivil_Adapter/Convert/ToBHoM/Properties/ToSectionProperty.cs
MidasCivil_Adapter/Convert/ToMidasCivil/Properties/FromSectionProperty.cs
MidasCivil_Adapter/MidasCivil_Adapter.csproj

https://github.com/BHoM/BHoM/pull/1030
https://github.com/BHoM/BHoM_Engine/pull/2063
Related to https://github.com/BHoM/BHoM/issues/756
- Aligning with migration of shape profiles from Geometry to Spatial

Aligning with changes to ShapeProfiles

---

MidasCivil_Adapter/CRUD/Read/Results/BarResults.cs
MidasCivil_Adapter/CRUD/Read/Results/MeshResults.cs
MidasCivil_Adapter/CRUD/Read/Results/ReadResults.cs

Closes #253 
This changes added functionality for results to by filtered by loadcase id and object.
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?originalPath=aHR0cHM6Ly9idXJvaGFwcG9sZC5zaGFyZXBvaW50LmNvbS86Zjovcy9CSG9NL0Vzb0dOaXp6OFZaQW5faDRWTlJoaHV3QlR1ajk4ZFZqNFpESzMtODRJRDhLR3c%5FcnRpbWU9Ylc4WjNzaGoyRWc&sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FMidasCivil%5FToolkit%2FMidasCivil%5FToolkit%2D%23253

Added ability to filter results by loadcase id and object

---

MidasCivil_Engine/MidasCivil_Engine.csproj
MidasCivil_Engine/Objects/MeshCentreComparer.cs

https://github.com/BHoM/BHoM_Engine/pull/2146/
https://github.com/BHoM/BHoM_Engine/issues/2135
Aligning with methods being removed from Structure_Engine.
This is only adding a reference and changing a to target another pre-existing method, so can safely be merged before others.

Aligning with changes in Structure_Engine

---

MidasCivil_Adapter/CRUD/Create/Loads/BarVaryingDistributedLoads.cs
MidasCivil_Adapter/CRUD/Read/Loads/BarVaryingDistributedLoads.cs
MidasCivil_Adapter/Convert/ToBHoM/Loads/ToBarVaryingDistributedLoad.cs
MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromBarVaryingDistributedLoad.cs

https://github.com/BHoM/BHoM/pull/1075
https://github.com/BHoM/BHoM_Engine/pull/2160
Aligns with changes to the BarVaryingDistributedLoad.
https://burohappold.sharepoint.com/:f:/s/BHoM/EhIZk-booZNHhaTeGJLSuMUB0TS-q8UA6_WxZH8crV4fWg?e=WkN1Ni

Updates to BarVaryingLoads

---

MidasCivil_Adapter/AdapterActions/Execute.cs
MidasCivil_Adapter/CRUD/Create/Elements/Element.cs
MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromFEMesh.cs
MidasCivil_Adapter/PrivateHelpers/CreateGroups.cs

Closes #254 
Allows for `FEMeshes` with more than one `Face` to be pushed into MidasCivil.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23254-Push_Mesh_to_MIdas?csf=1&web=1&e=qwLGjN

Push a mesh with more than one face

---

MidasCivil_Adapter/CRUD/Create/Create.cs
MidasCivil_Adapter/CRUD/Create/Loads/BarDifferentialTemperatureLoad.cs
MidasCivil_Adapter/CRUD/Read/Loads/BarDifferentialTemperatureLoad.cs
MidasCivil_Adapter/CRUD/Read/Loads/ReadLoad.cs
MidasCivil_Adapter/Convert/ToBHoM/Loads/ToBarDifferentialTemperatureLoad.cs
MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromBarDifferentialTemperatureLoad.cs
MidasCivil_Adapter/MidasCivilAdapter.cs
MidasCivil_Adapter/MidasCivil_Adapter.csproj

Closes #268 
Add Support for `BarDifferentialTemperatureLoad`. Please note that it is inputted in Midas as `BeamSectionTemperatures`. 
Add support for reading `BarDifferentialTemperatureLoad`.
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?cid=506a082e%2Daf0c%2D43ad%2D8fb5%2D4505bb1e26bb&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FArchive%2FMidasCivil%5FToolkit%2FMidasCivil%5FToolkit%2D%23268
- Add Support for `BarDifferentialTemperatureLoad`. Please note that it is inputted in Midas as `BeamSectionTemperatures`. 
- Add support for reading `BarDifferentialTemperatureLoad`.

Add support for BarDifferentialTemperatureLoad

---

MidasCivil_Adapter/AdapterActions/Execute.cs
MidasCivil_Adapter/CRUD/Create/Create.cs
MidasCivil_Adapter/CRUD/Create/Properties/Metadata.cs
MidasCivil_Adapter/CRUD/Read/Properties/ReadMetadata.cs
MidasCivil_Adapter/CRUD/Read/Read.cs
MidasCivil_Adapter/Convert/ToBHoM/Properties/ToMetadata.cs
MidasCivil_Adapter/Convert/ToMidasCivil/Properties/FromMetadata.cs
MidasCivil_Adapter/MidasCivilAdapter.cs
MidasCivil_Adapter/MidasCivil_Adapter.csproj
MidasCivil_Adapter/PrivateHelpers/GetSectionText.cs
MidasCivil_Adapter/PrivateHelpers/SetUnits.cs
MidasCivil_Adapter/PrivateHelpers/SetVersion.cs
MidasCivil_Engine/Compute/CombineTextFiles.cs
MidasCivil_Engine/Convert/Date.cs
MidasCivil_Engine/Create/Metadata.cs
MidasCivil_Engine/Create/Review.cs
MidasCivil_Engine/MidasCivil_Engine.csproj
MidasCivil_oM/MidasCivil_oM.csproj
MidasCivil_oM/Settings/Metadata.cs
MidasCivil_oM/Settings/Review.cs

Closes #298 
I have added a function to push meta data, done some general tidying up, and formatting for the .mct file.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23298-MetaData?csf=1&web=1&e=iCzm8x
- Added `MetaData` object that stores various data to be stored that are relevant to the model
- This `MetaData` can be pushed to and pulled from MidasCivil

Create Component to Allow Meta Data to be added to MidasCivil #299

---

MidasCivil_Adapter/Properties/AssemblyInfo.cs
MidasCivil_Engine/Properties/AssemblyInfo.cs
MidasCivil_oM/Properties/AssemblyInfo.cs

Update Assembly Information to include description

Update Assembly Information

---

MidasCivil_Adapter/Convert/ToBHoM/Properties/ToMaterials.cs

https://github.com/BHoM/BHoM_Datasets/pull/122
Aligns hardcoded paths to datasets migrated to discipline superfolder.

Align with migration of Structures datasets to subfolder

---

MidasCivil_Adapter/Convert/ToBHoM/Elements/ToBar.cs
MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromBar.cs

https://github.com/BHoM/BHoM/pull/1579

Align with rename StartNode/EndNode to Start/End

---

MidasCivil_Engine/Compute/CombineTextFiles.cs
MidasCivil_Engine/Compute/FEMeshToPanel.cs
MidasCivil_Engine/Create/Metadata.cs

Closes #377 
By inspection/compliance check
- Added input parameters for `Create.Metadata` method;
- Added `ToBeRemoved` attribute to `PanelToFEMesh` convert method (that has long since been replaced in the Structure_Engine
- Fixed other beta-documentation-check failures

Fix beta-compliance-checks

---

MidasCivil_Adapter/Properties/AssemblyInfo.cs
MidasCivil_Engine/Properties/AssemblyInfo.cs
MidasCivil_oM/Properties/AssemblyInfo.cs

Update AssemblyFileVersion to 7.3
Remove previous version attributes

Update AssemblyFileVersion to 7.3

---

MidasCivil_Adapter/Convert/ToBHoM/Elements/ToRigidLink.cs
MidasCivil_Adapter/Convert/ToMidasCivil/Elements/FromRigidLink.cs
MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromAreaUniformlyDistributedLoad.cs
MidasCivil_Adapter/Convert/ToMidasCivil/Loads/FromPointForce.cs

Closes #382 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/MidasCivil_Toolkit/%23390-review-changes-in-midascivil-2024-v11?csf=1&web=1&e=WVmTn8
- Added functionality for Midas Civil 2024 v1.1 and v2.1;

Upgrade adapter for MidasCivil 2024 v1.1 and 2.1 

---

README.md

Adds the newer versions of Midas supported into the Wiki
Closes #

Add supported versions to ReadMe
